### ISSUE TITLE
"right-hand side of 'in' should be an object" - in color assignment

### ISSUE THREAD

**Issue by FlemmingH** [finscn/pixi-lighting#1]
` var light = new PIXI.lighting.PointLight(0xffffff, 1);`

Gives me the error:
`TypeError: right-hand side of 'in' should be an object, got number  :   pixi-lighting.js:102:9`

**Comment by finscn** [comment]
```
var pointLight = new PointLight({
    color: 0xffffff,
    brightness: 4,

    ambientColor: 0x555555,
    ambientBrightness: 0.6,

    position: {
        x: viewWidth / 2,
        y: viewHeight / 2,
        z: lightHeight,
    }
});
```

This project is not as same as pixi-lights .

**Comment by FlemmingH** [comment]
Yeah, it works !!! The Iight-intensity are perfectly balanced when using multiple lights. And a nice control over them. I really appreciate this!
